name = "TypeScript.Glimmer"
grammar = "glimmer_typescript"
path_suffixes = ["gts"]
block_comment = ["{{!-- ", " --}}"]
word_characters = []
scope_opt_in_language_servers = [
    "tailwindcss-language-server",
    "vscode-html-language-server",
    "emmet-language-server",
]
prettier_parser_name = "glimmer"
autoclose_before = ">})"

brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "{{", end = "}}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = false, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "`", end = "`", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "!--", end = " --", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "!", end = "", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
]

[overrides.element]
opt_into_language_servers = ["emmet-language-server"]

[overrides.string]
word_characters = ["-"]
opt_into_language_servers = ["tailwindcss-language-server"]
