id = "ember"
name = "Ember"
version = "0.0.2"
schema_version = 1
authors = ["James Lamont <james@getvero.com>", "Lou Greenwood"]
description = "Syntax Highlighting for Ember"
repository = "https://github.com/jylamont/zed-ember"

[grammars.glimmer]
repository = "https://github.com/ember-tooling/tree-sitter-glimmer"
commit = "da605af8c5999b43e6839b575eae5e6cafabb06f"

[grammars.glimmer_javascript]
repository = "https://github.com/NullVoxPopuli/tree-sitter-glimmer-javascript/"
commit = "7e8ea8cf39fc360cb97bd253442cd48e4f7a9ce3"

[grammars.glimmer_typescript]
repository = "https://github.com/NullVoxPopuli/tree-sitter-glimmer-typescript/"
commit = "4006128790efb58ca82a4492d8ef0983b260fc6a"

[language_servers.ember]
name = "Ember Language Server"
language = "Glimmer"
languages = [
    "Handlebars",
    "Glimmer",
    "JavaScript",
    "TypeScript",
    "JavaScript.Glimmer",
    "TypeScript.Glimmer",
]

# [language_servers.glint]
# name = "Glint"
# language = "Glimmer"
# languages = [
#     "Handlebars",
#     "Glimmer",
#     "JavaScript.glimmer",
#     "TypeScript.glimmer",
# ]

[language_servers.ember.language_ids]
"HTML" = "html"
"Handlebars" = "glimmer"
"Glimmer" = "glimmer"
"JavaScript.Glimmer" = "glimmer_javascript"
"TypeScript.Glimmer" = "glimmer_typescript"

# [language_servers.glint.language_ids]
# "HTML" = "html"
# "Handlebars" = "glimmer"
# "Glimmer" = "glimmer"
# "JavaScript.glimmer" = "glimmer_javascript"
# "TypeScript.glimmer" = "glimmer_typescript"

# Doesn't do anything!
# [language_servers.vscode-html-language-server.language_ids]
# "Handlebars" = "html"
# "Glimmer" = "html"

# [language_servers.emmet-language-server]
# name = "Emmet Language Server"
# language = "HTML"
# languages = [
#     "HTML",
#     "PHP",
#     "ERB",
#     "JavaScript",
#     "TSX",
#     "CSS",
#     "Handlebars",
#     "Glimmer",
# ]
