name = "Handlebars"
grammar = "glimmer"
path_suffixes = ["hbs", "gjs", "gts"]
block_comment = ["{{!-- ", " --}}"]
word_characters = ["-"]
scope_opt_in_language_servers = ["tailwindcss-language-server"]
prettier_parser_name = "glimmer"

brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = true, newline = true, not_in = [
        "string",
        "comment",
    ] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "`", end = "`", close = true, newline = false, not_in = [
        "string",
    ] },
]

[overrides.string]
word_characters = ["-"]
opt_into_language_servers = ["tailwindcss-language-server"]
