name = "Handlebars"
grammar = "glimmer"
path_suffixes = ["hbs"]
prettier_parser_name = "glimmer"
brackets = [
  { start = "{{", end = "}}", close = true, newline = true, not_in = ["comment", "string"] },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
]
